version: "3.8"
services:
    nginx:
        container_name: server
        image : nginx:stable-alpine
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/laravel

    php:
        container_name: app
        build:
            args:
                user: bibka
                uid: 1000
            context: docker/dockerfiles
            dockerfile: php.dockerfile
        volumes:
            - ./:/var/www/laravel
        depends_on:
            - mysql
            - nginx

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3316:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/database:/var/lib/mysql

#    composer:
#        build:
#            context: docker/dockerfiles
#            dockerfile: php.dockerfile
#        volumes:
#            - .:/var/www/laravel
#        entrypoint:
#          [ 'composer', '--ignore-platform-reqs' ]
#
#    artisan:
#        build:
#            context: docker/dockerfiles
#            dockerfile: php.dockerfile
#        volumes:
#            - .:/var/www/laravel
#        entrypoint:
#          ["php", "/var/www/laravel/artisan"]
#        depends_on:
#            - mysql
#            - php
